//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNworking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C222_NotificationFunctionList
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Subject { get; set; }
        public int STT { get; set; }
        public string TimeSend { get; set; }
        public Nullable<int> Data { get; set; }
        public string Body { get; set; }
        public int DataTime { get; set; }
        public int DataTimeTo { get; set; }
        public int DataTimeFrom { get; set; }
    }
}
