//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNworking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C222_TimeCardDetail
    {
        public int ID { get; set; }
        public string StaffID { get; set; }
        public System.DateTime Date { get; set; }
        public System.DateTime InTime { get; set; }
        public System.DateTime OutTime { get; set; }
        public bool Deleted { get; set; }
    }
}
