//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNworking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C222_StokerTool
    {
        public int ID { get; set; }
        public string ToolNo { get; set; }
        public string ToolName { get; set; }
        public int Unit { get; set; }
        public string CatergoryID { get; set; }
    }
}
