//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNworking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C222_LeaderMonthlyInput
    {
        public int ID { get; set; }
        public System.DateTime Date { get; set; }
        public int Month { get; set; }
        public string DeptCode { get; set; }
        public string InputStaff { get; set; }
        public int ReciveQty { get; set; }
        public int CompleteQty { get; set; }
        public int IncompleteQty { get; set; }
        public double MachineCapa { get; set; }
        public double ErrorRate { get; set; }
        public int CriticalIssue { get; set; }
        public int IncompleteIssue { get; set; }
        public int KaizenApplied { get; set; }
    }
}
