//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNworking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C222_Shift
    {
        public int ID { get; set; }
        public string Shift { get; set; }
        public string Description { get; set; }
        public int Time { get; set; }
        public Nullable<bool> Milk { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime FinishTime { get; set; }
        public int Start { get; set; }
        public int Finish { get; set; }
    }
}
