//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNworking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C222_MeetingUploadFile
    {
        public int ID { get; set; }
        public int MeetingID { get; set; }
        public int CommentID { get; set; }
        public string FileName { get; set; }
        public string FilePath { get; set; }
        public bool Deleted { get; set; }
    }
}
