//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNworking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C222_MeetingContent
    {
        public int ID { get; set; }
        public System.DateTime Date { get; set; }
        public string Staff { get; set; }
        public string Subject { get; set; }
        public string Solution { get; set; }
        public string Command { get; set; }
        public Nullable<System.DateTime> Deadline { get; set; }
        public string Evaluate { get; set; }
        public Nullable<bool> Confirmed { get; set; }
        public bool Deleted { get; set; }
    }
}
