//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNworking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C222_WebUrl
    {
        public int ID { get; set; }
        public string Controller { get; set; }
        public string Action { get; set; }
        public string LocalPath { get; set; }
        public string Note { get; set; }
        public Nullable<bool> Updated { get; set; }
    }
}
