//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNworking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C222_StokerPurchase
    {
        public Nullable<int> ID { get; set; }
        public System.DateTime Date { get; set; }
        public string StaffID { get; set; }
        public string ToolID { get; set; }
        public int Quantity { get; set; }
        public bool Accepted { get; set; }
        public Nullable<System.DateTime> AcceptDate { get; set; }
        public bool Finished { get; set; }
        public Nullable<System.DateTime> FinishDate { get; set; }
    }
}
