//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNworking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C222_DayWork
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string datename { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<bool> NBStatus { get; set; }
        public string Des { get; set; }
    }
}
