//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNworking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C222_MaterialStock_Input
    {
        public int ID { get; set; }
        public System.DateTime Date { get; set; }
        public string Code { get; set; }
        public string MaterialID { get; set; }
        public string MaterialConfiguration { get; set; }
        public int Weight { get; set; }
        public Nullable<int> Qty { get; set; }
        public string Unit { get; set; }
        public string Note { get; set; }
    }
}
