//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNworking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C222_WorkflowInstance
    {
        public int ID { get; set; }
        public Nullable<int> WorkFollow { get; set; }
        public string ModuleName { get; set; }
        public Nullable<int> CurrentStep { get; set; }
        public Nullable<int> Status { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string Note { get; set; }
    }
}
