//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNworking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C222_StockerItem
    {
        public int ID { get; set; }
        public string ItemID { get; set; }
        public string ItemName { get; set; }
        public Nullable<int> PurchasingUnit { get; set; }
        public Nullable<int> UsingUnit { get; set; }
        public Nullable<int> MOQ { get; set; }
        public Nullable<int> Rounding { get; set; }
        public Nullable<int> Catergory { get; set; }
        public Nullable<int> Supplier { get; set; }
        public Nullable<int> Maker { get; set; }
        public Nullable<int> Type { get; set; }
        public string Note { get; set; }
        public Nullable<int> Lenght { get; set; }
        public Nullable<int> MeCutLenght { get; set; }
        public Nullable<int> MeNumber { get; set; }
    }
}
