//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNworking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C222_WorkFolowInstanceHistory
    {
        public int ID { get; set; }
        public Nullable<int> InstanceID { get; set; }
        public Nullable<int> StepID { get; set; }
        public Nullable<int> StepAction { get; set; }
        public string ActionBy { get; set; }
        public Nullable<System.DateTime> ActionDate { get; set; }
        public string Commment { get; set; }
        public Nullable<int> StatusAfterAction { get; set; }
        public string ModuleName { get; set; }
    }
}
