//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNworking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C222_LeaderDailyInput
    {
        public int ID { get; set; }
        public System.DateTime Date { get; set; }
        public string DeptCode { get; set; }
        public string InputStaff { get; set; }
        public int WorkingEmployee { get; set; }
        public int Staff2Machine { get; set; }
        public int WorkingMachine { get; set; }
        public int ProblemMachine { get; set; }
        public int EmptyMachine { get; set; }
        public int FaultyProduct { get; set; }
        public int IncompleteError { get; set; }
        public int ErrorOnDay { get; set; }
        public int IssueWithOther { get; set; }
        public int UrgentItem { get; set; }
        public int UrgentItemCompleted { get; set; }
        public int NeedQty { get; set; }
        public int FinishQty { get; set; }
    }
}
