//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNworking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C222_PurChase
    {
        public int ID { get; set; }
        public string PurchaseID { get; set; }
        public string Subject { get; set; }
        public System.DateTime InputDate { get; set; }
        public string StaffID { get; set; }
        public Nullable<System.DateTime> TimeNeed { get; set; }
        public Nullable<System.DateTime> AvailableTime { get; set; }
        public Nullable<bool> Complete { get; set; }
        public string Note { get; set; }
    }
}
