//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNworking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C222_StokerCatergory
    {
        public int ID { get; set; }
        public Nullable<int> MenuType { get; set; }
        public string Catergory { get; set; }
        public string Alias { get; set; }
        public string Note { get; set; }
    }
}
