//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNworking.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class C222_WorkflowStep
    {
        [Key]
        public int ID { get; set; }
        public Nullable<int> WorkFollowID { get; set; }
        public Nullable<int> StepOder { get; set; }
        public string StepName { get; set; }
        public Nullable<int> RoleID { get; set; }
        public Nullable<int> ActionType { get; set; }
        public Nullable<int> NextStepOnApprove { get; set; }
        public Nullable<int> NextStepOnReject { get; set; }
        public bool IsFinal { get; set; }
    }
}
