//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNworking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C222_LeaderWeeklyInput
    {
        public int ID { get; set; }
        public System.DateTime Date { get; set; }
        public int Week { get; set; }
        public string DeptCode { get; set; }
        public string InputStaff { get; set; }
        public double MachineRate { get; set; }
        public double EmployeeRate { get; set; }
        public double ErrorRate { get; set; }
        public int CriticalError { get; set; }
        public int ReciveQty { get; set; }
        public int CompleteQty { get; set; }
        public int IncompleteQty { get; set; }
        public int ErrorQty { get; set; }
        public int ErrorComplete { get; set; }
        public int ErrorIncomplete { get; set; }
        public int IssueOnWeek { get; set; }
        public int Kaizen { get; set; }
    }
}
