//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNworking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C222_Users
    {
        public string UserName { get; set; }
        public string Password { get; set; }
        public int UserGroupID { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public string StaffID { get; set; }
    }
}
