//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNworking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C222_StaffShift
    {
        public int ID { get; set; }
        public string StaffID { get; set; }
        public System.DateTime Date { get; set; }
        public string Shift { get; set; }
        public string Lunch { get; set; }
        public string Dinner { get; set; }
        public bool Milk { get; set; }
        public System.DateTime ShiftTimeStart { get; set; }
        public System.DateTime ShiftTimeFinish { get; set; }
        public System.DateTime StartWork { get; set; }
        public System.DateTime FinishWork { get; set; }
    }
}
