//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNworking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C222_CarRegister
    {
        public int ID { get; set; }
        public System.DateTime Date { get; set; }
        public string RegStaff { get; set; }
        public System.DateTime NeedDate { get; set; }
        public System.DateTime EstimatedEndTime { get; set; }
        public string Reason { get; set; }
        public bool Accepted { get; set; }
        public string Car { get; set; }
        public Nullable<bool> Support { get; set; }
        public string SupportReason { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> FinishTime { get; set; }
        public bool Completed { get; set; }
        public string Note { get; set; }
        public bool Deleted { get; set; }
    }
}
