//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNworking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C222_StockerOutputDEtail
    {
        public int ID { get; set; }
        public string Number { get; set; }
        public string OderCan { get; set; }
        public int SlgCan { get; set; }
        public string OrderCo { get; set; }
        public int SlgCo { get; set; }
        public bool GiayXN { get; set; }
    }
}
