//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNworking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C222_StokerOrder
    {
        public int ID { get; set; }
        public System.DateTime Date { get; set; }
        public string Dept { get; set; }
        public string StaffID { get; set; }
        public string Reason { get; set; }
        public System.DateTime TimeNeed { get; set; }
        public Nullable<System.DateTime> AvailableTime { get; set; }
        public bool Accept { get; set; }
        public bool ItemAvailable { get; set; }
    }
}
