//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNworking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C242_OptionData2
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> InputDate { get; set; }
        public string PartID { get; set; }
        public string MachineID { get; set; }
        public string OptionID { get; set; }
        public Nullable<bool> LastOption { get; set; }
        public string JigID { get; set; }
        public Nullable<int> ToolQty { get; set; }
        public Nullable<double> ProTime { get; set; }
        public Nullable<double> ClampTime { get; set; }
        public Nullable<bool> TechDate { get; set; }
        public Nullable<System.DateTime> UpdateDay { get; set; }
        public string StaffID { get; set; }
        public string Note { get; set; }
        public string AondNote { get; set; }
        public string Memo { get; set; }
        public Nullable<System.DateTime> CLUpdateday { get; set; }
        public string JigType { get; set; }
        public Nullable<bool> Jig { get; set; }
        public Nullable<double> Tich { get; set; }
        public Nullable<double> Doc { get; set; }
        public Nullable<double> TimeTreo { get; set; }
        public Nullable<double> TimeComplete { get; set; }
        public bool Deleted { get; set; }
    }
}
