//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNworking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C242_ShiftHandOver
    {
        public int ID { get; set; }
        public System.DateTime Date { get; set; }
        public string Shift { get; set; }
        public string HandOverPersion { get; set; }
        public int HandOverItem { get; set; }
        public string HandOverContent { get; set; }
        public string HandOverRecipient { get; set; }
        public Nullable<bool> HandOverRecipientConfirm { get; set; }
    }
}
