//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNworking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C242_StandTimeManualChecking
    {
        public int ID { get; set; }
        public System.DateTime Date { get; set; }
        public string Shift { get; set; }
        public string MachineID { get; set; }
        public string PartID { get; set; }
        public string OptionID { get; set; }
        public string WorkID { get; set; }
        public string Sub_WorkID { get; set; }
        public string Staff { get; set; }
        public System.DateTime CheckingTime { get; set; }
        public System.DateTime ExpectedProcessingTime { get; set; }
        public bool Checking { get; set; }
        public string Leader { get; set; }
        public Nullable<bool> ConfirmOK { get; set; }
        public Nullable<bool> ConfirmNG { get; set; }
        public string ConfirmContent { get; set; }
        public Nullable<System.DateTime> ConfirmTime { get; set; }
        public string ConfirmCode { get; set; }
        public string MONo { get; set; }
        public int PlannID { get; set; }
    }
}
