//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNworking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C242_MechanicalElectronicalWork
    {
        public int ID { get; set; }
        public string WorkContent { get; set; }
        public string Nature { get; set; }
        public System.DateTime RequestDate { get; set; }
        public string RequestStaff { get; set; }
        public string RequestDept { get; set; }
        public System.DateTime Deadline { get; set; }
        public Nullable<System.DateTime> CompleteDate { get; set; }
        public string MainPIC { get; set; }
        public string Status { get; set; }
        public string Result { get; set; }
        public string InCompleteReason { get; set; }
        public string Note { get; set; }
    }
}
