//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNworking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C242_WTS
    {
        public int ID { get; set; }
        public Nullable<int> IDPlan { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string StaffID { get; set; }
        public string Shift { get; set; }
        public string MachineID { get; set; }
        public string OptionID { get; set; }
        public string MONo { get; set; }
        public string PartID { get; set; }
        public string WorkID { get; set; }
        public Nullable<decimal> Time { get; set; }
        public Nullable<int> OKQty { get; set; }
        public Nullable<int> NGQty { get; set; }
        public Nullable<double> ProTime { get; set; }
        public Nullable<double> ClampTime { get; set; }
        public string Note { get; set; }
        public string Note1 { get; set; }
        public string Note2 { get; set; }
        public Nullable<bool> Status { get; set; }
        public bool Deleted { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> FinishTime { get; set; }
        public Nullable<bool> OVT { get; set; }
        public string LeaderCheck { get; set; }
        public Nullable<System.DateTime> CheckTime { get; set; }
        public Nullable<int> SoBuoc { get; set; }
        public Nullable<int> Buoc { get; set; }
        public Nullable<int> OKBuoc { get; set; }
        public Nullable<int> NGBuoc { get; set; }
        public Nullable<int> NGNCTruoc { get; set; }
        public Nullable<bool> WorkWhilePLJ1 { get; set; }
    }
}
