//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNworking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C242_Part
    {
        public int ID { get; set; }
        public string PartNo { get; set; }
        public string PartName { get; set; }
        public string CustomerID { get; set; }
        public string SupplierID { get; set; }
        public Nullable<int> UpQty { get; set; }
        public int CatID { get; set; }
        public string Unit { get; set; }
        public bool IsTool { get; set; }
        public Nullable<int> GiaThanh { get; set; }
        public bool Deleted { get; set; }
        public Nullable<double> NVL { get; set; }
        public Nullable<double> LoiNhuan { get; set; }
        public Nullable<double> VanChuyen { get; set; }
        public Nullable<double> MotGio { get; set; }
        public Nullable<double> TachNC { get; set; }
        public Nullable<double> DoGa { get; set; }
        public Nullable<bool> Phoi { get; set; }
        public Nullable<bool> File_HD { get; set; }
        public Nullable<bool> Dao { get; set; }
        public Nullable<bool> Jig { get; set; }
    }
}
