//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNworking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C242_Prepare_Processing
    {
        public int ID { get; set; }
        public System.DateTime Date { get; set; }
        public string MachineID { get; set; }
        public string PartID { get; set; }
        public string OptionID { get; set; }
        public string Command { get; set; }
        public string Priority { get; set; }
        public string CB_StaffID { get; set; }
        public Nullable<System.DateTime> CB_Start { get; set; }
        public Nullable<System.DateTime> CB_End { get; set; }
        public string CT_StaffID { get; set; }
        public Nullable<System.DateTime> CT_Start { get; set; }
        public Nullable<System.DateTime> CT_End { get; set; }
        public string SX_StaffID { get; set; }
        public Nullable<System.DateTime> SX_Start { get; set; }
        public Nullable<System.DateTime> SX_End { get; set; }
        public string Note { get; set; }
        public string CB_Note { get; set; }
        public string CT_Note { get; set; }
        public string SX_Note { get; set; }
        public Nullable<System.DateTime> KH_TGCT { get; set; }
        public Nullable<System.DateTime> KH_TGCB { get; set; }
        public Nullable<System.DateTime> KH_TGCTh { get; set; }
        public string KH_Note { get; set; }
        public string PBStaff { get; set; }
    }
}
