//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNworking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C242_Dulieudonhangmoi
    {
        public Nullable<System.DateTime> Date { get; set; }
        public string BusOrder { get; set; }
        public Nullable<bool> Gctho { get; set; }
        public Nullable<System.DateTime> NgayDKM { get; set; }
        public Nullable<System.DateTime> NgayDKNCKTra { get; set; }
        public Nullable<System.DateTime> NgayDKNCVia { get; set; }
        public Nullable<System.DateTime> NgaycoPhoi { get; set; }
    }
}
