//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNworking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C242_ManualExcution
    {
        public int ID { get; set; }
        public string CheckingContent { get; set; }
        public string CheckingTool { get; set; }
        public bool HeightPrice { get; set; }
        public Nullable<int> IndexNumber { get; set; }
    }
}
