//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNworking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C242_MachinePlan_Preparation
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string PartID { get; set; }
        public string MachineID { get; set; }
        public string OptionID { get; set; }
        public string PBJ1_Staff { get; set; }
        public string CB_Staff { get; set; }
        public string GL_Staff { get; set; }
        public string PBJ1_Time { get; set; }
        public Nullable<int> STT { get; set; }
        public string Note { get; set; }
        public Nullable<bool> Phoi_KH { get; set; }
        public Nullable<bool> File_CB { get; set; }
        public Nullable<bool> File_KT { get; set; }
        public Nullable<bool> CT_CB { get; set; }
        public Nullable<bool> CT_KT { get; set; }
        public Nullable<bool> DG_CB { get; set; }
        public Nullable<bool> DG_KT { get; set; }
        public Nullable<bool> Dao_CB { get; set; }
        public Nullable<bool> Dao_KT { get; set; }
        public string Confirmation { get; set; }
    }
}
