//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNworking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C242_TechJob2
    {
        public int ID { get; set; }
        public string RequestDept { get; set; }
        public string JobContent { get; set; }
        public string WorkDes { get; set; }
        public string CompletedPercen { get; set; }
        public Nullable<System.DateTime> Deadline { get; set; }
        public string Note { get; set; }
    }
}
