//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNworking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C242_MachinePlanning_view
    {
        public int ID { get; set; }
        public string Order { get; set; }
        public string NC { get; set; }
        public string MayGC { get; set; }
        public Nullable<int> Slglenh { get; set; }
        public Nullable<System.DateTime> BatDau { get; set; }
        public Nullable<System.DateTime> KetThuc { get; set; }
        public Nullable<double> TGGC { get; set; }
        public Nullable<double> TGGL { get; set; }
        public string TenChiTiet { get; set; }
        public string K { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Shift { get; set; }
        public Nullable<System.DateTime> ThoiHan { get; set; }
        public Nullable<int> TinhTrang { get; set; }
        public string DKmay { get; set; }
        public string SoJig { get; set; }
        public string TTNC { get; set; }
        public string Dept { get; set; }
        public string Jig { get; set; }
        public string Note { get; set; }
        public string LastOption { get; set; }
        public Nullable<System.DateTime> RegisterDate { get; set; }
        public Nullable<int> C10_ { get; set; }
        public Nullable<int> C20_ { get; set; }
        public Nullable<int> C80_ { get; set; }
        public string Via_check1 { get; set; }
        public string Via_check2 { get; set; }
        public string Via_ghi_chu { get; set; }
        public Nullable<System.DateTime> Fac_NgayHTtheoKH { get; set; }
        public Nullable<int> Fac_TT { get; set; }
        public string Fac_NGTruoc { get; set; }
        public string Fac_TTFile { get; set; }
        public Nullable<bool> Fac_Phoi { get; set; }
        public Nullable<bool> Fac_File { get; set; }
        public Nullable<bool> Fac_Dao { get; set; }
        public Nullable<bool> Fac_Jig { get; set; }
        public Nullable<int> Fac_TTTH { get; set; }
        public Nullable<bool> Fac_DaChuanBi { get; set; }
        public Nullable<bool> Fac_TTGC { get; set; }
        public string Fac_DeXuat { get; set; }
        public Nullable<int> Fac_OK_Old { get; set; }
        public Nullable<int> Fac_NG_Old { get; set; }
        public Nullable<bool> Fac_Dc { get; set; }
        public string Fac_MachineID { get; set; }
        public Nullable<bool> Fac_GCXong { get; set; }
        public Nullable<bool> Fac_GCDo { get; set; }
        public Nullable<bool> Fac_TTFileMem { get; set; }
        public Nullable<bool> Fac_ThaoTac { get; set; }
        public Nullable<double> KT_TGTC_HT { get; set; }
        public string KT_Sup { get; set; }
        public Nullable<double> KT_TGUKB1 { get; set; }
        public Nullable<double> KT_TongTG { get; set; }
        public Nullable<int> KT_TTPhoi { get; set; }
        public string KT_GiaHang { get; set; }
        public string KT_KHXN { get; set; }
        public string KT_LyDoKHTKH { get; set; }
        public string KT_DgoiTay { get; set; }
        public Nullable<bool> MachineStatus { get; set; }
        public Nullable<bool> PreparationMachine { get; set; }
        public Nullable<System.DateTime> Cua_GCTime { get; set; }
        public string Cua_Factory { get; set; }
        public Nullable<double> Cua_TotalTime { get; set; }
        public Nullable<double> Cua_Plantime { get; set; }
        public string Cua_PrepareDate { get; set; }
        public string Cua_MachineGroup { get; set; }
        public Nullable<bool> Cua_State { get; set; }
        public string Cua_Size { get; set; }
        public Nullable<bool> Cua_PrepareState { get; set; }
        public Nullable<bool> Pre_State { get; set; }
        public Nullable<System.DateTime> Pre_ConfirmDate { get; set; }
        public string TongTG { get; set; }
        public string Phoidd { get; set; }
        public string Nesting { get; set; }
        public Nullable<bool> ProcessInFreely { get; set; }
        public string ViTriGia { get; set; }
        public bool Deleted { get; set; }
    }
}
