//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNworking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C242_StandTimeAffectationCode
    {
        public int ID { get; set; }
        public int STT { get; set; }
        public string Categories { get; set; }
        public string ContentText { get; set; }
        public string WorkID { get; set; }
        public string Sub_WorkID { get; set; }
    }
}
