//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNworking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C242_TrackingViTri
    {
        public int ID { get; set; }
        public string DeptCode { get; set; }
        public string GiaCode { get; set; }
        public string GiaDe { get; set; }
        public string Tang { get; set; }
        public string Thung { get; set; }
    }
}
