//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNworking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C242_ManualExcutionChecking
    {
        public int ID { get; set; }
        public int ExcutionConten { get; set; }
        public string Tool { get; set; }
        public bool Checked { get; set; }
        public System.DateTime CheckTime { get; set; }
        public string MachineID { get; set; }
        public string StaffID { get; set; }
        public string MONo { get; set; }
        public int MOQty { get; set; }
        public string PartNo { get; set; }
        public string OptionID { get; set; }
        public int PartNoIndex { get; set; }
        public string Shift { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
