//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNworking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C242_ToolReturn
    {
        public int ID { get; set; }
        public string ToolID { get; set; }
        public string ToolName { get; set; }
        public string ToolMakerName { get; set; }
        public int Quantity { get; set; }
        public bool ReturnTool { get; set; }
        public Nullable<System.DateTime> ReturnTime { get; set; }
        public bool Acception { get; set; }
        public Nullable<System.DateTime> AcceptTime { get; set; }
        public int BorrowNo { get; set; }
    }
}
