//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNworking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C242_MOOption
    {
        public int ID { get; set; }
        public string MONo { get; set; }
        public string PartID { get; set; }
        public Nullable<int> MOQty { get; set; }
        public Nullable<System.DateTime> Deadline { get; set; }
        public string MachineID { get; set; }
        public string OptionID { get; set; }
        public Nullable<bool> LastOption { get; set; }
        public string JigType { get; set; }
        public Nullable<double> ProTime { get; set; }
        public Nullable<double> ClampTime { get; set; }
        public Nullable<bool> Finished { get; set; }
        public Nullable<System.DateTime> Finishdate { get; set; }
        public string Shift { get; set; }
        public string Note { get; set; }
        public bool Deleted { get; set; }
    }
}
