//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNworking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C242_Work
    {
        public int ID { get; set; }
        public string WorkID { get; set; }
        public string WorkName { get; set; }
        public bool DirectWork { get; set; }
        public bool MachWork { get; set; }
        public Nullable<bool> MachInDWork { get; set; }
        public Nullable<bool> MachineRun { get; set; }
        public string GroupID { get; set; }
        public string DeptCode { get; set; }
        public Nullable<int> SortingNumber { get; set; }
        public bool OptionDataWork { get; set; }
        public bool MassWork { get; set; }
        public bool InspecWork { get; set; }
        public bool StopWork { get; set; }
        public string DeptOption { get; set; }
    }
}
