//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNworking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C242_InventoryExportHistory
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string ExportOrder { get; set; }
        public string SharedOrder { get; set; }
        public int SharedQty { get; set; }
        public string Note { get; set; }
    }
}
