//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNworking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C242_ErrorItemNotify
    {
        public int ID { get; set; }
        public string MONo { get; set; }
        public string OptionID { get; set; }
        public string PartID { get; set; }
        public int ErrorNumber { get; set; }
        public string NotifyDept { get; set; }
        public int ErrorTypeID { get; set; }
        public string ErrorContent { get; set; }
        public System.DateTime NotifyDate { get; set; }
        public System.DateTime ReceiveErrorItemDate { get; set; }
        public string Note { get; set; }
        public string Supplier { get; set; }
        public string RaiseErrorDept { get; set; }
        public string ErrorComment { get; set; }
        public string CauseOfError { get; set; }
        public Nullable<int> Evaluate { get; set; }
        public bool Deleted { get; set; }
    }
}
