//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNworking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C242_StandTime
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string PartNo { get; set; }
        public string MachineID { get; set; }
        public string OptionID { get; set; }
        public Nullable<double> ProTime { get; set; }
        public Nullable<double> ClampTime { get; set; }
        public Nullable<double> PJ61_PKN1 { get; set; }
        public Nullable<double> PZE1 { get; set; }
        public Nullable<double> PBJ1 { get; set; }
        public Nullable<double> PU71 { get; set; }
        public Nullable<double> PH71 { get; set; }
        public string Note { get; set; }
        public string Note2 { get; set; }
        public Nullable<int> NumberOption { get; set; }
        public Nullable<bool> Status { get; set; }
        public string MachineGroup { get; set; }
    }
}
