//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNworking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C242_YCKP
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string OrderNo { get; set; }
        public string OptionID { get; set; }
        public string MachineID { get; set; }
        public Nullable<System.DateTime> DateYCKP { get; set; }
        public string YCKPContent { get; set; }
        public string SolutionContent { get; set; }
        public Nullable<System.DateTime> DateYCKPDeadline { get; set; }
        public Nullable<System.DateTime> YCKPProcessTime { get; set; }
        public string RaiseDept { get; set; }
        public string InputStaff { get; set; }
        public string ProcessStaff { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public string UpdateStaff { get; set; }
    }
}
