//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNworking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C242_MO
    {
        public string MONo { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string PartID { get; set; }
        public Nullable<int> MOQty { get; set; }
        public Nullable<System.DateTime> DeadLine { get; set; }
        public Nullable<int> HelisertQty { get; set; }
        public Nullable<int> BlastQty { get; set; }
        public Nullable<bool> Started { get; set; }
        public Nullable<System.DateTime> startdate { get; set; }
        public Nullable<bool> Finished { get; set; }
        public Nullable<System.DateTime> Finishdate { get; set; }
        public Nullable<int> OKQty { get; set; }
        public Nullable<int> NGQty { get; set; }
        public Nullable<bool> Imported { get; set; }
        public string Note { get; set; }
        public int ID { get; set; }
        public Nullable<int> SPQty { get; set; }
        public Nullable<bool> AutoStart { get; set; }
        public Nullable<System.DateTime> AutoStartTime { get; set; }
    }
}
