//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNworking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C242_MaintenanceCheck
    {
        public int ID { get; set; }
        public string MachineId { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string PrevValue { get; set; }
        public string AfterValue { get; set; }
        public string Quantity { get; set; }
        public string OilV5 { get; set; }
        public string Oil68 { get; set; }
        public string LeakOK { get; set; }
        public string ElectricalOK { get; set; }
        public string BodyOK { get; set; }
        public string ProcessStaff { get; set; }
        public string CheckedStaff { get; set; }
        public Nullable<bool> Deleted { get; set; }
    }
}
