//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNworking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C242_ToolBorrowDetail
    {
        public int ID { get; set; }
        public Nullable<int> BorrowNo { get; set; }
        public Nullable<bool> BorrowNew { get; set; }
        public Nullable<bool> BorrowMore { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Note { get; set; }
        public string ToolDataID { get; set; }
        public string ToolName { get; set; }
        public string MakerToolName { get; set; }
        public Nullable<bool> Available { get; set; }
    }
}
