//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNworking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C242_ToolsNeedForProcessing
    {
        public int ID { get; set; }
        public string MachineID { get; set; }
        public string PartNo { get; set; }
        public string OptionID { get; set; }
        public Nullable<int> Buoc { get; set; }
        public string Option { get; set; }
        public string TenDao { get; set; }
        public string KHDao { get; set; }
        public string ToolID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Note { get; set; }
    }
}
