//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNworking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C242_ResultOfCheckMachineProcess
    {
        public int ID { get; set; }
        public string PartID { get; set; }
        public string MONo { get; set; }
        public string OptionID { get; set; }
        public string MachineID { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string Staff_PB { get; set; }
        public string Staff_PL { get; set; }
        public Nullable<bool> TotalResult { get; set; }
        public Nullable<bool> Phoi { get; set; }
        public Nullable<bool> Jig { get; set; }
        public Nullable<bool> Dao { get; set; }
        public Nullable<bool> SizeForCheck { get; set; }
        public Nullable<bool> CheDoCat { get; set; }
        public Nullable<bool> PPCat { get; set; }
        public Nullable<bool> MayGC { get; set; }
        public Nullable<bool> PPGC { get; set; }
        public Nullable<bool> Status { get; set; }
        public string Username { get; set; }
        public string DeviceCheck { get; set; }
        public Nullable<double> G54X { get; set; }
        public Nullable<double> G54Y { get; set; }
        public Nullable<double> G54Z { get; set; }
        public Nullable<double> G55X { get; set; }
        public Nullable<double> G55Y { get; set; }
        public Nullable<double> G55Z { get; set; }
        public Nullable<double> G56X { get; set; }
        public Nullable<double> G56Y { get; set; }
        public Nullable<double> G56Z { get; set; }
        public Nullable<double> G57X { get; set; }
        public Nullable<double> G57Y { get; set; }
        public Nullable<double> G57Z { get; set; }
        public Nullable<double> G58X { get; set; }
        public Nullable<double> G58Y { get; set; }
        public Nullable<double> G58Z { get; set; }
        public Nullable<double> G59X { get; set; }
        public Nullable<double> G59Y { get; set; }
        public Nullable<double> G59Z { get; set; }
    }
}
