//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNworking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C242_YCKP_Response
    {
        public int ID { get; set; }
        public string UpdatedStaff { get; set; }
        public string UpdatedDept { get; set; }
        public System.DateTime Date { get; set; }
        public string Status { get; set; }
        public string UpdatedResponse { get; set; }
        public string UpdatedReason { get; set; }
        public string UpdatedSolution { get; set; }
    }
}
