//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNworking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C242_MaintenanceBug
    {
        public int ID { get; set; }
        public string MachineId { get; set; }
        public string CheckId { get; set; }
        public string Description { get; set; }
        public string Reporter { get; set; }
        public string FixWay { get; set; }
        public string FixDetail { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    }
}
