//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNworking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C242_ErrorItemNotify_View
    {
        public int ID { get; set; }
        public string ErrorNo { get; set; }
        public System.DateTime DateRaiseErr { get; set; }
        public System.DateTime DateWrite { get; set; }
        public string NotifyDept { get; set; }
        public string RaiseErrorDept { get; set; }
        public string NotifyStaff { get; set; }
        public string Supplier { get; set; }
        public string RaiseErrorStaff { get; set; }
        public string Customer { get; set; }
        public string ErrorType { get; set; }
        public string OrderNo { get; set; }
        public string PartID { get; set; }
        public int Qty { get; set; }
        public int ErrorQty { get; set; }
        public string OptionID { get; set; }
        public string ErrorDes { get; set; }
        public bool DecisionToFine { get; set; }
        public string NotPenalizeDes { get; set; }
        public int ErrorProcess { get; set; }
        public string ErrorCause { get; set; }
        public string Remedies { get; set; }
        public string Remedies1 { get; set; }
        public string Remedies2 { get; set; }
        public string ManagerRemedies { get; set; }
        public int ErrorContent { get; set; }
        public int DeceidedTime { get; set; }
        public int PredictErrorCause { get; set; }
        public int ErrorHappenFrequency { get; set; }
        public Nullable<bool> Completed { get; set; }
        public string PIC { get; set; }
        public string ViTriHang { get; set; }
        public Nullable<System.DateTime> Deadline { get; set; }
        public string Shift { get; set; }
        public string ErrorType1 { get; set; }
        public string ErrorType2 { get; set; }
        public string ErrorCause1 { get; set; }
        public string ErrorCause2 { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public string UpdateStaff { get; set; }
    }
}
