//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNworking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C242_TechJob1
    {
        public int ID { get; set; }
        public string RequestDept { get; set; }
        public string ItemCode { get; set; }
        public string OrderNo { get; set; }
        public string ContentChanged { get; set; }
        public string ValidateChange { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public string DrawingNo { get; set; }
        public string ChangedStaff { get; set; }
    }
}
