//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNworking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C333_Tool
    {
        public int ID { get; set; }
        public string ToolID { get; set; }
        public string ToolName { get; set; }
        public string MakerToolName { get; set; }
        public decimal Price { get; set; }
        public string FrequencyID { get; set; }
        public string ToolGroupID { get; set; }
        public Nullable<int> SafeQty { get; set; }
        public string MakerID { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
    }
}
