//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNworking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C333_Return
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string StaffID { get; set; }
        public string MachineID { get; set; }
        public string ToolID { get; set; }
        public string StatusName { get; set; }
        public int Quantity { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    }
}
