//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNworking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CS_Comment
    {
        public int ID { get; set; }
        public int CategoryID { get; set; }
        public string UserName { get; set; }
        public string StaffID { get; set; }
        public string Content { get; set; }
        public System.DateTime Date { get; set; }
        public bool IsSeen { get; set; }
        public Nullable<System.DateTime> DateSeen { get; set; }
        public string IP { get; set; }
        public int CheckSheetID { get; set; }
    }
}
