//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNworking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CS_CheckSheet
    {
        public int ID { get; set; }
        public System.DateTime Date { get; set; }
        public string CodeIsChecked { get; set; }
        public string CheckedBy { get; set; }
        public string Area { get; set; }
        public string Position { get; set; }
        public string OrderNo { get; set; }
        public string PartNo { get; set; }
        public int SubGroupID { get; set; }
        public bool Status { get; set; }
        public bool IsGroupLeaderConfirmed { get; set; }
        public Nullable<bool> IsAMConfirmed { get; set; }
        public string IsSTConfirmed { get; set; }
        public Nullable<System.DateTime> DateAMConfirmed { get; set; }
        public string ContentAMReject { get; set; }
        public Nullable<bool> IsMailSent { get; set; }
        public Nullable<bool> ManagerResponse { get; set; }
        public Nullable<System.DateTime> ResponseDate { get; set; }
        public Nullable<System.DateTime> DateComplete { get; set; }
    }
}
