//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNworking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CS_Category
    {
        public int ID { get; set; }
        public string Reference { get; set; }
        public string Require { get; set; }
        public bool Status { get; set; }
        public string WorkName { get; set; }
        public int SubGroupID { get; set; }
        public int Index { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> RemoveDate { get; set; }
        public string GroupCategoryID { get; set; }
        public string CreateCode { get; set; }
        public string RemoveCode { get; set; }
        public string ImageStandard { get; set; }
    }
}
