//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNworking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CS_SubGroup
    {
        public int ID { get; set; }
        public string SubGroup { get; set; }
        public string GroupID { get; set; }
        public string GroupLeader { get; set; }
        public Nullable<bool> IsDailyReport { get; set; }
        public string Superior { get; set; }
        public string Position { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<bool> Status { get; set; }
        public string CreateCode { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string PositionCheck { get; set; }
        public string AreaCheck { get; set; }
        public string CoSuperior { get; set; }
        public Nullable<int> DayInMonth { get; set; }
        public Nullable<int> PriodicAmount { get; set; }
        public string PriodicUnit { get; set; }
        public Nullable<int> DayRemind { get; set; }
    }
}
