//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNworking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DES_DrawingInfo
    {
        public int Id { get; set; }
        public string TECNOLOGY { get; set; }
        public string CUSTOMER { get; set; }
        public string FAB { get; set; }
        public string AMAT_PART { get; set; }
        public string MFG_PART { get; set; }
        public string MFG_SERIAL { get; set; }
        public string SUPPLIER_PROJ { get; set; }
        public string INVOICE { get; set; }
        public string CONFIG_MODIFED { get; set; }
        public string STATUS { get; set; }
        public string PO { get; set; }
        public Nullable<System.DateTime> STARTUP_DATE { get; set; }
        public string COMMENTS { get; set; }
        public string OPP_ID { get; set; }
        public string BU { get; set; }
        public string PLATFORM { get; set; }
        public Nullable<System.DateTime> NEED_DATE { get; set; }
        public string DELIVERY_LOCATION { get; set; }
        public string PRICE { get; set; }
        public string CATEGORY { get; set; }
        public string ITEM { get; set; }
        public string PART_NUMBERS_SUPPLIER { get; set; }
        public string PART_NUMBERS_AMAT { get; set; }
        public string QTY { get; set; }
        public string PRODUCT_NAME { get; set; }
        public Nullable<System.DateTime> REVISED_MRP_DATE { get; set; }
        public Nullable<System.DateTime> COMMIT_DATE { get; set; }
        public Nullable<System.DateTime> FORECAST_NEED_DATE { get; set; }
        public string LOAD_PORT_ORDER { get; set; }
        public string CUSTOMER_FAMILY { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string CreatedBy { get; set; }
    }
}
