//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNworking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DES_Platform_DrawingDWG
    {
        public int Id { get; set; }
        public string Platform { get; set; }
        public string Version { get; set; }
        public string Drawing_GSD_EN_DWG { get; set; }
        public string Drawing_GSD1_EN_DWG { get; set; }
        public string Drawing_GSD2_EN_DWG { get; set; }
        public string Drawing_GSD_JP_DWG { get; set; }
        public string Drawing_GSD1_JP_DWG { get; set; }
        public string Drawing_GSD2_JP_DWG { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> Deleted { get; set; }
        public string DeletedBy { get; set; }
    }
}
