//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNworking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DES_Drawing_FullOption
    {
        public int Id { get; set; }
        public string Label { get; set; }
        public string Categories { get; set; }
        public string Item { get; set; }
        public string Description { get; set; }
        public string Platform { get; set; }
        public string Partnumber_Supplier { get; set; }
        public string Partnumber_AMAT { get; set; }
        public string AMAT_Description { get; set; }
        public Nullable<decimal> UnitCost_USD { get; set; }
        public Nullable<int> RowIndex { get; set; }
        public string LayerName_InDWGFile { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> Deleted { get; set; }
        public string DeletedBy { get; set; }
    }
}
