//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNworking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Form_ListForm_DefineField
    {
        public int Id { get; set; }
        public Nullable<int> Id_Form { get; set; }
        public string FieldKey { get; set; }
        public string FieldName { get; set; }
        public string FieldType { get; set; }
        public string FieldHeader { get; set; }
        public string Caption { get; set; }
        public string Description { get; set; }
        public string Page { get; set; }
        public Nullable<int> AxisX { get; set; }
        public Nullable<int> AxisY { get; set; }
        public Nullable<int> Width { get; set; }
        public Nullable<int> Height { get; set; }
        public Nullable<int> Length { get; set; }
        public Nullable<int> Size { get; set; }
        public Nullable<decimal> Opacity { get; set; }
        public string Color { get; set; }
        public string DrawType { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> Deleted { get; set; }
        public string DeletedBy { get; set; }
        public string CellValueInExcel { get; set; }
        public string FieldNameLink { get; set; }
        public Nullable<int> FieldNameLink_Id { get; set; }
        public string FieldLink_ColumnShow { get; set; }
        public Nullable<int> FieldLink_ColumnShow_Id { get; set; }
        public Nullable<int> Id_FromOldVersion { get; set; }
        public Nullable<bool> Required { get; set; }
        public Nullable<int> Id_Proccess_Enable { get; set; }
    }
}
