//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNworking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Form_DirectManagement
    {
        public int Id { get; set; }
        public string DeptId { get; set; }
        public string StaffId { get; set; }
        public string DirectManagementStaffId { get; set; }
        public string DirectManagementEmail { get; set; }
        public string OfficeStaffId { get; set; }
        public string OfficeEmail { get; set; }
        public string GroupName { get; set; }
        public string AMStaffId { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<int> Id_SP { get; set; }
        public string Pass { get; set; }
    }
}
