//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNworking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Form_ListForm
    {
        public int Id { get; set; }
        public string Dept { get; set; }
        public string Categories { get; set; }
        public string FormId { get; set; }
        public string FormName { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsApprove { get; set; }
        public string Status { get; set; }
        public string Approver { get; set; }
        public Nullable<System.DateTime> Approved { get; set; }
        public Nullable<int> Version { get; set; }
        public Nullable<bool> PublicToCompany { get; set; }
        public Nullable<bool> OnlyDept { get; set; }
        public Nullable<bool> IsPublished { get; set; }
        public Nullable<System.DateTime> Published { get; set; }
        public string PublishedBy { get; set; }
        public string FileType { get; set; }
        public string FileNameImport { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> Deleted { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<int> Id_Approval_Process { get; set; }
        public string ApproveContent { get; set; }
    }
}
