//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNworking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Form_RequestList
    {
        public int Id { get; set; }
        public string DeptId { get; set; }
        public string Id_Request { get; set; }
        public Nullable<int> Id_Form { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> Deleted { get; set; }
        public string DeletedBy { get; set; }
        public string ApproverId { get; set; }
        public string ApproverName { get; set; }
        public string ShareFor { get; set; }
        public string ShareForName { get; set; }
        public string Status { get; set; }
        public string CurrentUserAccess { get; set; }
        public Nullable<int> Id_Approval_Process { get; set; }
        public string CurrentStepName_Approve_Process { get; set; }
        public string AllUserAttend { get; set; }
        public Nullable<bool> Attachment { get; set; }
        public Nullable<int> CurrentProcessHistory { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string ModifiedBy { get; set; }
    }
}
