//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNworking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Form_FieldType_LinkData
    {
        public int Id { get; set; }
        public string FieldType { get; set; }
        public string ColumnValue { get; set; }
        public string ColumnName { get; set; }
        public string TableName { get; set; }
        public string WhereColumn { get; set; }
        public string Query { get; set; }
    }
}
