//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNworking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Form_RequestList_Process_History
    {
        public int Id { get; set; }
        public Nullable<int> IdRequest { get; set; }
        public string StaffId { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string ApproveContent { get; set; }
        public Nullable<bool> IsApprove { get; set; }
        public Nullable<int> Id_ProcessDefine { get; set; }
        public string StaffIdNext { get; set; }
    }
}
