//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNworking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_AllowanceShift
    {
        public int Id { get; set; }
        public string StaffId { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<int> Per10 { get; set; }
        public Nullable<int> Per35 { get; set; }
        public Nullable<int> Per50 { get; set; }
        public Nullable<int> Per70 { get; set; }
        public Nullable<int> Per90 { get; set; }
    }
}
