//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNworking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_DSGiayNghi
    {
        public int Id { get; set; }
        public string TenPhong { get; set; }
        public string NguoiXinNghi { get; set; }
        public string Code { get; set; }
        public string LoaiNghi { get; set; }
        public string LoaiGiayNghi { get; set; }
        public Nullable<System.DateTime> TuNgay { get; set; }
        public Nullable<System.DateTime> DenNgay { get; set; }
        public string LyDo { get; set; }
        public string Status { get; set; }
        public Nullable<double> SoNgayNghi { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string CreatedBy { get; set; }
        public string DuyetGiayXinNghi { get; set; }
        public string DuyetGiayXinNghi_x0028_1_x0029_ { get; set; }
        public Nullable<int> IdSP { get; set; }
        public string NguoiDuyet { get; set; }
        public Nullable<System.DateTime> InputDate { get; set; }
        public string InputBy { get; set; }
    }
}
