//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNworking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_DSGiayNghi_QuaTrinhDuyet
    {
        public int Id { get; set; }
        public Nullable<int> IdGiayNghi { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string NguoiXuLy { get; set; }
        public string NoiDungXuLy { get; set; }
        public Nullable<int> IdSP { get; set; }
    }
}
