//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNworking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_OldPassXinNghi
    {
        public int Id { get; set; }
        public string StaffId { get; set; }
        public string OldPass { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
    }
}
