//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNworking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_Recruiment_Candidate
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Receiveddate { get; set; }
        public string ProfileId { get; set; }
        public string Source { get; set; }
        public string PositionId { get; set; }
        public string StaffId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string FullName { get; set; }
        public string VNFirstName { get; set; }
        public string VNLastName { get; set; }
        public string VNFullName { get; set; }
        public Nullable<System.DateTime> BirthDay { get; set; }
        public Nullable<int> Gender { get; set; }
        public string Nationality { get; set; }
        public string Religion { get; set; }
        public string Nation { get; set; }
        public string IdentityCardNumber { get; set; }
        public string PlaceIssua { get; set; }
        public Nullable<System.DateTime> DateOfIssua { get; set; }
        public Nullable<int> MaritalStatus { get; set; }
        public Nullable<int> Children { get; set; }
        public string ResidenceAddress { get; set; }
        public string Residence_Village_Ward { get; set; }
        public string ResidenceDistrict { get; set; }
        public string ResidenceCity { get; set; }
        public string TemporaryAddress { get; set; }
        public string Temporary_Village_Ward { get; set; }
        public string Temporary_District { get; set; }
        public string Temporary_City { get; set; }
        public string PersonEmail { get; set; }
        public string PhoneNumber { get; set; }
        public string SchoolName { get; set; }
        public Nullable<int> EducationMode { get; set; }
        public string EducationLevel { get; set; }
        public string Majors { get; set; }
        public Nullable<decimal> Toeic { get; set; }
        public Nullable<decimal> Ielts { get; set; }
        public Nullable<decimal> Toefl { get; set; }
        public Nullable<int> Japan { get; set; }
        public Nullable<int> China { get; set; }
        public Nullable<int> Korean { get; set; }
        public string OtherLanguage { get; set; }
        public Nullable<bool> Office { get; set; }
        public Nullable<bool> Autocad2D { get; set; }
        public Nullable<bool> Autocad3D { get; set; }
        public Nullable<bool> AutodeskInventor { get; set; }
        public string OtherSkill { get; set; }
        public string WorkInRRC { get; set; }
        public string WorkInJapanCompany { get; set; }
        public Nullable<decimal> YearExperience { get; set; }
        public string Experience { get; set; }
        public string Note { get; set; }
        public string Picture { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> Deleted { get; set; }
        public string DeletedBy { get; set; }
        public string Status { get; set; }
        public string IsApprove { get; set; }
        public Nullable<System.DateTime> IsApproved { get; set; }
        public string IsApprovedBy { get; set; }
        public string PositionIdOld { get; set; }
        public string ApprovedComment { get; set; }
        public string HistoryApproval { get; set; }
        public Nullable<int> IdStage { get; set; }
        public Nullable<int> IdPhaseTest { get; set; }
        public Nullable<int> IdProfile { get; set; }
        public Nullable<System.DateTime> TestDate { get; set; }
    }
}
