//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNworking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_Recruiment_Position_Define_Details
    {
        public int Id { get; set; }
        public Nullable<int> Id_Position_Define { get; set; }
        public Nullable<bool> Male { get; set; }
        public Nullable<bool> Female { get; set; }
        public Nullable<int> MinAge { get; set; }
        public Nullable<int> MaxAge { get; set; }
        public string EducationLevel { get; set; }
        public Nullable<int> ModeOfStudy { get; set; }
        public string Majors { get; set; }
        public string MajorsGroup { get; set; }
        public Nullable<decimal> Min_YearExperience { get; set; }
        public Nullable<decimal> Max_YearExperience { get; set; }
        public string JobDescription { get; set; }
        public string Priority { get; set; }
        public Nullable<bool> English { get; set; }
        public Nullable<int> Toeic_From { get; set; }
        public Nullable<int> Toeic_To { get; set; }
        public Nullable<decimal> Ielts_From { get; set; }
        public Nullable<decimal> Ielts_To { get; set; }
        public Nullable<decimal> Toefl_From { get; set; }
        public Nullable<decimal> Toefl_To { get; set; }
        public Nullable<int> Japanese { get; set; }
        public Nullable<int> Chinese { get; set; }
        public Nullable<int> Korean { get; set; }
        public string OtherLanguage { get; set; }
        public Nullable<decimal> OtherLanguage_From { get; set; }
        public Nullable<decimal> OtherLanguage_To { get; set; }
        public Nullable<bool> Office { get; set; }
        public Nullable<bool> AutoCad2D { get; set; }
        public Nullable<bool> AutoCad3D { get; set; }
        public Nullable<bool> AutodeskInventor { get; set; }
        public string ComputerSkill { get; set; }
        public string ComputerSkill_Other { get; set; }
        public Nullable<decimal> Height { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<bool> GoodHealth { get; set; }
        public string OthersHealth { get; set; }
        public Nullable<bool> BrightEyes { get; set; }
        public string OtherRequest { get; set; }
        public string Experience { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> Deleted { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<int> IdOld { get; set; }
    }
}
