//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNworking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_StaffProfile_WorkInformation
    {
        public int Id { get; set; }
        public int IdProfile { get; set; }
        public Nullable<int> IdDept { get; set; }
        public Nullable<int> IdGroup { get; set; }
        public Nullable<int> IdSubGroup { get; set; }
        public Nullable<int> IdPosition { get; set; }
        public Nullable<System.DateTime> DateStart { get; set; }
        public Nullable<System.DateTime> DateFinish { get; set; }
        public Nullable<bool> IsCurrent { get; set; }
        public string ChangeContent { get; set; }
        public Nullable<int> IdDecision { get; set; }
        public string CompanyEmail { get; set; }
        public string Class { get; set; }
        public Nullable<int> Status { get; set; }
        public string ApproverWTS { get; set; }
        public string ApproverWTS2 { get; set; }
        public string ApproverWTS3 { get; set; }
        public string ApproverLeaveForm { get; set; }
        public string BusStationCode { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> Deleted { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<int> IsDirect { get; set; }
        public string ReasonType { get; set; }
        public string Reason { get; set; }
        public Nullable<System.DateTime> DateOfApplication { get; set; }
        public Nullable<System.DateTime> DateOfLastWork { get; set; }
        public string CompanyGroupEmail { get; set; }
    }
}
