//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNworking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_StaffProfile_WorkProcess_WaitApprove
    {
        public int Id { get; set; }
        public Nullable<int> IdProfile { get; set; }
        public string DateFrom { get; set; }
        public string DateTo { get; set; }
        public string WorkPlace { get; set; }
        public string Department { get; set; }
        public string Position { get; set; }
        public string StartSalary { get; set; }
        public string EndSalary { get; set; }
        public string ReasonEnd { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> Deleted { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<bool> IsApprove { get; set; }
        public Nullable<System.DateTime> IsApproved { get; set; }
        public string IsApprovedBy { get; set; }
    }
}
