//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNworking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_StaffProfile_Education
    {
        public int Id { get; set; }
        public Nullable<int> IdProfile { get; set; }
        public string DateFrom { get; set; }
        public string DateTo { get; set; }
        public string IdSchool { get; set; }
        public string EducationLevel { get; set; }
        public string IdMajors { get; set; }
        public string GraduatedDate { get; set; }
        public Nullable<int> GraduatedKind { get; set; }
        public string CerfiticateType { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> Deleted { get; set; }
        public string DeletedBy { get; set; }
    }
}
