//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNworking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_StaffProfile_ForeignLanguage_WaitApprove
    {
        public int Id { get; set; }
        public Nullable<int> IdProfile { get; set; }
        public Nullable<int> IdLanguage { get; set; }
        public Nullable<int> IdLevel { get; set; }
        public Nullable<bool> Certificate { get; set; }
        public Nullable<decimal> Mark { get; set; }
        public Nullable<System.DateTime> ValidDate { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
        public string Listening { get; set; }
        public string Speaking { get; set; }
        public string Reading { get; set; }
        public string Writing { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> Deleted { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<bool> IsApprove { get; set; }
        public Nullable<System.DateTime> IsApproved { get; set; }
        public string IsApprovedBy { get; set; }
    }
}
