//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNworking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_LayNClamKHGcong03
    {
        public Nullable<System.DateTime> Date { get; set; }
        public string PartID { get; set; }
        public string NC { get; set; }
        public Nullable<System.DateTime> ProDeadline { get; set; }
        public string MachineID { get; set; }
        public string ActualMachine { get; set; }
        public string JigType { get; set; }
        public string JigID { get; set; }
        public string PlanNo { get; set; }
        public string MONumber { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<int> MOQty { get; set; }
        public string Material { get; set; }
        public Nullable<double> ProTime { get; set; }
        public Nullable<double> ClampTime { get; set; }
        public Nullable<double> Expr1 { get; set; }
        public string BOderNo { get; set; }
        public Nullable<bool> LastOption { get; set; }
        public Nullable<int> Changetooltimes { get; set; }
        public Nullable<bool> Jig { get; set; }
        public Nullable<System.DateTime> UpdateDay { get; set; }
        public string Note2 { get; set; }
        public string Note { get; set; }
        public Nullable<bool> Gctho { get; set; }
        public Nullable<System.DateTime> NgaycoPhoi { get; set; }
        public Nullable<System.DateTime> NgayDKM { get; set; }
        public string StaffID { get; set; }
        public Nullable<int> TongNC { get; set; }
        public string SoNc { get; set; }
    }
}
