//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNworking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quiz_Exam_Slots
    {
        public long Id { get; set; }
        public Nullable<int> IdQuiz_Exam { get; set; }
        public Nullable<int> Slot { get; set; }
        public Nullable<int> IdGroupQuestion { get; set; }
        public Nullable<int> IdQuestion { get; set; }
        public string Type { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string ModifiedBy { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Mark { get; set; }
    }
}
