//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNworking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quiz_Question
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> IdGroupQuestion { get; set; }
        public Nullable<int> IdParent { get; set; }
        public string ContentQuestion { get; set; }
        public double DefaultMark { get; set; }
        public Nullable<double> Penalty { get; set; }
        public int QuestionType { get; set; }
        public System.DateTime Created { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public Nullable<short> Status { get; set; }
        public string ModifiedBy { get; set; }
        public string PictureLink { get; set; }
        public string Import { get; set; }
        public string Type { get; set; }
    }
}
