//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNworking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quiz_Answers
    {
        public int Id { get; set; }
        public int IdQuestion { get; set; }
        public string ContenAnswer { get; set; }
        public Nullable<bool> IsTrue { get; set; }
        public string PictureLink { get; set; }
        public Nullable<short> Status { get; set; }
    }
}
