//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNworking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quiz_Exams
    {
        public int Id { get; set; }
        public int ExamGroupId { get; set; }
        public string Name { get; set; }
        public System.DateTime TimeOpen { get; set; }
        public System.DateTime TimeClose { get; set; }
        public int TimeLimit { get; set; }
        public System.DateTime Created { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<double> GradesMark { get; set; }
        public Nullable<short> Status { get; set; }
        public string Description { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> RepeatTimes { get; set; }
    }
}
