//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNworking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quiz_Exam_Attempt
    {
        public int Id { get; set; }
        public Nullable<int> ExamsId { get; set; }
        public string StaffId { get; set; }
        public string QuestionLayOut { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> TimeStart { get; set; }
        public Nullable<System.DateTime> TimeFinish { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public Nullable<double> MarkTotal { get; set; }
        public Nullable<int> Remaintime { get; set; }
        public string Picture { get; set; }
        public Nullable<int> IsMark { get; set; }
        public string MarkBy { get; set; }
        public Nullable<System.DateTime> Marked { get; set; }
        public Nullable<System.DateTime> MarkModified { get; set; }
        public string MarkModifiedBy { get; set; }
        public string ModifiedContent { get; set; }
        public Nullable<System.DateTime> ExamDate { get; set; }
        public Nullable<bool> IsCancel { get; set; }
        public Nullable<System.DateTime> Canceled { get; set; }
        public string CanceledBy { get; set; }
        public string Result { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string CreatedBy { get; set; }
    }
}
