//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNworking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RP_DefineCheckReport
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string PartNo { get; set; }
        public Nullable<int> IdGroup { get; set; }
        public string FileName { get; set; }
        public string CreateBy { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Supplier { get; set; }
        public string Customer { get; set; }
        public string FormNo { get; set; }
        public string ApproveBy { get; set; }
        public Nullable<double> Version { get; set; }
        public string FormExport { get; set; }
        public Nullable<bool> IsInspection { get; set; }
        public Nullable<System.DateTime> StopDate { get; set; }
        public Nullable<System.DateTime> FApproveDate { get; set; }
        public Nullable<System.DateTime> IApproveDate { get; set; }
        public string IApproveBy { get; set; }
    }
}
