//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNworking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SM_CurrentPosition
    {
        public int ID { get; set; }
        public bool Status { get; set; }
        public string StaffID { get; set; }
        public string CurrentPosition { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string StaffIDCreate { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public string StaffIDDelete { get; set; }
        public string WorkStatus { get; set; }
        public string Level { get; set; }
        public string Certificate { get; set; }
        public string GroupName { get; set; }
    }
}
