//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNworking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SM_DailyReport
    {
        public int ID { get; set; }
        public string StaffID { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> ContentAmount { get; set; }
        public Nullable<int> TimeAmount { get; set; }
        public Nullable<int> KnowledgeLevel { get; set; }
        public Nullable<int> TrainingMethod { get; set; }
        public string ContentRepeat { get; set; }
        public string LessonEvaluate { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime LastModified { get; set; }
        public string LastCode { get; set; }
        public bool InUse { get; set; }
        public string MentorApprove { get; set; }
        public Nullable<System.DateTime> MentorDate { get; set; }
        public string TrainingLeader { get; set; }
        public Nullable<System.DateTime> TrainingDate { get; set; }
        public string ContentLeader { get; set; }
    }
}
