//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNworking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SM_InitialTraining
    {
        public int ID { get; set; }
        public string Code { get; set; }
        public string Content { get; set; }
        public string CodeTraining { get; set; }
        public string Result { get; set; }
        public System.DateTime Date { get; set; }
    }
}
