//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNworking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SM_SkillResult
    {
        public int ID { get; set; }
        public string Code { get; set; }
        public string CodeTraining { get; set; }
        public string CodeEvaluate { get; set; }
        public Nullable<double> Score { get; set; }
        public Nullable<bool> Result { get; set; }
        public Nullable<System.DateTime> DateTraining { get; set; }
        public Nullable<System.DateTime> DateEvaluate { get; set; }
        public string Note { get; set; }
        public int SkillID { get; set; }
        public string Certificate { get; set; }
        public bool Status { get; set; }
        public Nullable<int> StandardTime { get; set; }
        public Nullable<int> ExecutingTime { get; set; }
        public Nullable<double> TheoryScore { get; set; }
    }
}
