//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNworking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SM_TrainingProgram
    {
        public string Group { get; set; }
        public string Worker { get; set; }
        public string Checker { get; set; }
        public string Inspector { get; set; }
        public string Trainer { get; set; }
        public string Other { get; set; }
        public Nullable<System.DateTime> WorkerDate { get; set; }
        public Nullable<System.DateTime> CheckerDate { get; set; }
        public Nullable<System.DateTime> InspectorDate { get; set; }
        public Nullable<System.DateTime> TrainerDate { get; set; }
        public Nullable<System.DateTime> OtherDate { get; set; }
        public string Note { get; set; }
    }
}
