//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNworking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SM_WorkPosition
    {
        public int ID { get; set; }
        public string Code { get; set; }
        public System.DateTime DateIn { get; set; }
        public string Degree { get; set; }
        public int WorkID { get; set; }
        public System.DateTime DateCreate { get; set; }
        public string CodeCreate { get; set; }
        public string Group { get; set; }
        public string Description { get; set; }
    }
}
