//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNworking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffListCheck202002
    {
        public string Code { get; set; }
        public string Name { get; set; }
        public string Dept { get; set; }
        public string Sex { get; set; }
        public string CMT { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> Birthdate { get; set; }
        public Nullable<System.DateTime> HiredDate { get; set; }
        public int Id { get; set; }
    }
}
