//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNworking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Training_Stage_Attend_Staff
    {
        public int Id { get; set; }
        public Nullable<int> Id_Stage { get; set; }
        public string Dept { get; set; }
        public string StaffId { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> Deleted { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<bool> IsComplete { get; set; }
        public Nullable<System.DateTime> Completed { get; set; }
        public string CompletedBy { get; set; }
        public Nullable<int> TotalContent { get; set; }
        public Nullable<int> Times { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<bool> IsConfirm { get; set; }
        public Nullable<System.DateTime> Confirmed { get; set; }
        public string ConfirmedBy { get; set; }
        public Nullable<bool> IsApprove { get; set; }
        public Nullable<System.DateTime> Approved { get; set; }
        public string ApprovedBy { get; set; }
    }
}
