//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNworking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Training_Stage
    {
        public int Id { get; set; }
        public string Stage { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> FinishDate { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> Deleted { get; set; }
        public string DeletedBy { get; set; }
        public string SendTo1 { get; set; }
        public Nullable<System.DateTime> SendDate1 { get; set; }
        public string SendBy1 { get; set; }
        public string SendTo2 { get; set; }
        public Nullable<System.DateTime> SendDate2 { get; set; }
        public string SendBy2 { get; set; }
        public string SendTo3 { get; set; }
        public Nullable<System.DateTime> SendDate3 { get; set; }
        public string SendBy3 { get; set; }
        public Nullable<System.DateTime> Confirmed { get; set; }
        public string ConfirmedBy { get; set; }
        public Nullable<System.DateTime> Approved { get; set; }
        public string ApprovedBy { get; set; }
        public string Status { get; set; }
        public string Reason { get; set; }
    }
}
