//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNworking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_242_PartData
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> InputDate { get; set; }
        public string PartID { get; set; }
        public string MaterialID { get; set; }
        public string MaterialType { get; set; }
        public string Workpiecesize { get; set; }
        public string shape { get; set; }
        public Nullable<double> Thickness { get; set; }
        public string width { get; set; }
        public Nullable<double> lenght { get; set; }
        public Nullable<bool> Cut { get; set; }
        public Nullable<bool> RawMachine { get; set; }
        public Nullable<bool> HandFinish { get; set; }
        public Nullable<bool> HairLine { get; set; }
        public Nullable<bool> WAnod { get; set; }
        public Nullable<bool> BAnod { get; set; }
        public Nullable<bool> Blast30 { get; set; }
        public Nullable<bool> Blast60 { get; set; }
        public Nullable<bool> Seal { get; set; }
        public Nullable<bool> Migaki { get; set; }
        public Nullable<bool> Bafu { get; set; }
        public Nullable<bool> Cleanwave { get; set; }
        public Nullable<bool> VacPac { get; set; }
        public Nullable<bool> Helisert { get; set; }
        public Nullable<bool> SerialNo { get; set; }
        public Nullable<bool> PalCoat { get; set; }
        public Nullable<bool> Paint { get; set; }
        public Nullable<bool> BBD { get; set; }
        public string Otherpro { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Memo { get; set; }
        public string Note { get; set; }
        public Nullable<bool> Caciras { get; set; }
        public Nullable<bool> Inside { get; set; }
        public Nullable<bool> MaBong { get; set; }
        public Nullable<bool> InLuoi { get; set; }
        public Nullable<bool> Heru { get; set; }
        public Nullable<bool> Niken { get; set; }
        public Nullable<bool> MaiBongDP { get; set; }
        public Nullable<int> CofigID { get; set; }
        public bool Deleted { get; set; }
    }
}
