//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNworking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_222_ShiftRegister
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string StaffID { get; set; }
        public string Shift { get; set; }
        public Nullable<System.DateTime> Income { get; set; }
        public Nullable<System.DateTime> Outcome { get; set; }
        public Nullable<int> WorkTime { get; set; }
        public Nullable<bool> Lunch { get; set; }
        public Nullable<bool> Dinner { get; set; }
        public bool Breakfast { get; set; }
        public bool Milk { get; set; }
        public bool Deleted { get; set; }
        public string UserDelete { get; set; }
        public string MachineID { get; set; }
        public string Note { get; set; }
    }
}
