//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNworking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_ManualExcutionChecking_GetTotal
    {
        public Nullable<int> CheckedNumber { get; set; }
        public string MachineID { get; set; }
        public string MONo { get; set; }
        public string PartNo { get; set; }
        public string OptionID { get; set; }
        public Nullable<System.DateTime> CheckTime { get; set; }
        public Nullable<int> MOQty { get; set; }
        public Nullable<int> NeedItemNumber { get; set; }
        public string PartNoIndex { get; set; }
        public int Number { get; set; }
    }
}
