//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNworking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_222_StokerMenu
    {
        public int ID { get; set; }
        public int CatergoryID { get; set; }
        public int ParentID { get; set; }
        public string Note { get; set; }
        public string SubCat { get; set; }
        public string SubAlias { get; set; }
        public string MainCat { get; set; }
        public string MainAlias { get; set; }
    }
}
