//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNworking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_242_Option
    {
        public int ID { get; set; }
        public string DeptCode { get; set; }
        public string OptionID { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> InputTime { get; set; }
        public bool Deleted { get; set; }
    }
}
