//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNworking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_242_YCKPXL
    {
        public int ID { get; set; }
        public string OrderNo { get; set; }
        public string OptionID { get; set; }
        public string MachineID { get; set; }
        public string PartId { get; set; }
        public System.DateTime Deadline { get; set; }
        public string RankLevel { get; set; }
        public int ProcessProduct { get; set; }
        public int YCKPTimes { get; set; }
        public string ProcessStatus { get; set; }
        public string YCKPContent { get; set; }
        public string CauseContent { get; set; }
        public string SolutionContent { get; set; }
        public System.DateTime YCKPDate { get; set; }
        public System.DateTime YCKPDeadline { get; set; }
        public System.DateTime YCKPProcessTime { get; set; }
        public string InputStaff { get; set; }
        public string InputDept { get; set; }
        public string ProcessStaff { get; set; }
        public string ProcessDept { get; set; }
        public string ResponseId { get; set; }
        public string Status { get; set; }
        public bool Deleted { get; set; }
        public string UpdatedStaff { get; set; }
        public string UpdatedDept { get; set; }
        public string UpdatedResponse { get; set; }
        public string UpdatedReason { get; set; }
        public string UpdatedSolution { get; set; }
        public string CausedDept { get; set; }
        public string CausedDetail { get; set; }
    }
}
