//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNworking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_222_MaterialStock
    {
        public int ID { get; set; }
        public string MaterialID { get; set; }
        public string Supplier { get; set; }
        public string Code { get; set; }
        public string Note { get; set; }
        public Nullable<int> InputWeight { get; set; }
        public Nullable<int> OutputWeight { get; set; }
        public Nullable<int> AvailableWeight { get; set; }
    }
}
