//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNworking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_242_InventoryReceivedDetail
    {
        public int ID { get; set; }
        public int VoucherID { get; set; }
        public string PartNo { get; set; }
        public string OrderNumber { get; set; }
        public int Qty { get; set; }
        public decimal Price { get; set; }
        public string Note { get; set; }
        public string NguoiNhan { get; set; }
        public int StatusID { get; set; }
        public bool Deleted { get; set; }
        public string GiaDe { get; set; }
        public Nullable<bool> ReceivedConfirm { get; set; }
        public Nullable<System.DateTime> ReceivedConfirmTime { get; set; }
        public string ReceivedConfirmStaff { get; set; }
    }
}
