//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNworking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Tracking_History
    {
        public Nullable<int> ID { get; set; }
        public Nullable<int> VoucherID { get; set; }
        public string PartNo { get; set; }
        public string OrderNumber { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Note { get; set; }
        public string NguoiNhan { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public string GiaDe { get; set; }
        public Nullable<bool> ReceivedConfirm { get; set; }
        public Nullable<System.DateTime> ReceivedConfirmTime { get; set; }
        public string ReceivedConfirmStaff { get; set; }
        public System.DateTime Date { get; set; }
        public string StaffID { get; set; }
        public bool Import { get; set; }
        public string ImportFrom { get; set; }
        public string ReceiveDept { get; set; }
        public string TotalNote { get; set; }
    }
}
