//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNworking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_222_Machine
    {
        public int ID { get; set; }
        public string MachineID { get; set; }
        public string MakerMachineNo { get; set; }
        public string AccName { get; set; }
        public string DensanName { get; set; }
        public string DensanCode { get; set; }
        public string Dmachine { get; set; }
        public string MachineName { get; set; }
        public string MachineGR { get; set; }
        public string Maker { get; set; }
        public Nullable<decimal> Charge { get; set; }
        public Nullable<double> Ratio { get; set; }
        public Nullable<bool> kakokikai { get; set; }
        public Nullable<bool> MultiPalet { get; set; }
        public string MGroup { get; set; }
        public string SGroup { get; set; }
        public Nullable<bool> tranfer { get; set; }
        public string MachineGroup { get; set; }
        public string MachineWTS { get; set; }
        public string OriginalMachine { get; set; }
        public Nullable<bool> Active { get; set; }
        public bool Deleted { get; set; }
    }
}
