//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNworking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Welfare_Rule
    {
        public int Id { get; set; }
        public string Type { get; set; }
        public string Id_Relative { get; set; }
        public Nullable<bool> LiveTogether { get; set; }
        public Nullable<int> Min_Month { get; set; }
        public Nullable<int> Max_Month { get; set; }
        public Nullable<int> Times { get; set; }
        public Nullable<int> NoOfChild { get; set; }
        public Nullable<int> DayOff { get; set; }
        public Nullable<int> Amount { get; set; }
        public string Gift { get; set; }
    }
}
