//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNworking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Welfare_V_StaffProfile
    {
        public int Id { get; set; }
        public Nullable<int> Type { get; set; }
        public string DeptId { get; set; }
        public string ShortName { get; set; }
        public string DeptShortName { get; set; }
        public string StaffId { get; set; }
        public string VNFullName { get; set; }
        public Nullable<System.DateTime> BirthDay { get; set; }
        public Nullable<int> Gender { get; set; }
        public string IdentityCardNumber { get; set; }
        public string PlaceIssua { get; set; }
        public Nullable<System.DateTime> DateOfIssua { get; set; }
        public Nullable<int> MaritalStatus { get; set; }
        public Nullable<int> Children { get; set; }
        public string ResidenceAddress { get; set; }
        public string ResidenceDistrict { get; set; }
        public string ResidenceCity { get; set; }
        public string TemporaryAddress { get; set; }
        public string Temporary_Village_Ward { get; set; }
        public string Temporary_District { get; set; }
        public string Temporary_City { get; set; }
        public string PhoneNumber { get; set; }
        public string PersonEmail { get; set; }
        public string EducationLevel { get; set; }
        public Nullable<System.DateTime> DateStart { get; set; }
    }
}
