//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNworking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Welfare_PayList
    {
        public int Id { get; set; }
        public string PayNo { get; set; }
        public Nullable<int> Total { get; set; }
        public Nullable<int> Time { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string CreatedBy { get; set; }
        public string Approver { get; set; }
        public Nullable<System.DateTime> Approved { get; set; }
        public Nullable<System.DateTime> Deleted { get; set; }
        public string DeletedBy { get; set; }
        public string Status { get; set; }
    }
}
