//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNworking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Welfare_List
    {
        public int Id { get; set; }
        public string Id_Form { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Dept { get; set; }
        public string Type { get; set; }
        public string Reason { get; set; }
        public string Description { get; set; }
        public string RelativeClass { get; set; }
        public string Relative { get; set; }
        public Nullable<int> Id_Relative { get; set; }
        public string NameOfRelative { get; set; }
        public Nullable<int> NoOfChild { get; set; }
        public Nullable<int> Times { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public string Place { get; set; }
        public string Address { get; set; }
        public string InteringPlace { get; set; }
        public Nullable<bool> LiveTogether { get; set; }
        public Nullable<int> SettlementAmount { get; set; }
        public string Flower { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> DayOff { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> Deleted { get; set; }
        public string DeletedBy { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string ModifiedBy { get; set; }
        public string Manager_Approver { get; set; }
        public Nullable<System.DateTime> Manager_Approved { get; set; }
        public string Manager_Approve { get; set; }
        public string GA_Approver { get; set; }
        public Nullable<System.DateTime> GA_Approved { get; set; }
        public string GA_Approve { get; set; }
        public string ACC_Approver { get; set; }
        public Nullable<System.DateTime> ACC_Approved { get; set; }
        public string ACC_Approve { get; set; }
        public Nullable<int> Id_Sharepoint { get; set; }
        public Nullable<bool> IsPay { get; set; }
        public Nullable<System.DateTime> Payed { get; set; }
        public string PayedBy { get; set; }
        public string Id_WorkFlow { get; set; }
        public string All_Approver { get; set; }
        public Nullable<int> Id_Pay { get; set; }
    }
}
